# GoReleaser configuration for Aixgo
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    # Run tests before release
    - go test ./...
    # Ensure go.mod is tidy
    - go mod tidy

builds:
  # Orchestrator CLI
  - id: orchestrator
    main: ./cmd/orchestrator
    binary: aixgo-orchestrator
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # Benchmark CLI
  - id: benchmark
    main: ./cmd/benchmark
    binary: aixgo-benchmark
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # Deploy CLI
  - id: deploy
    main: ./cmd/deploy
    binary: aixgo-deploy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # Tools CLI
  - id: tools
    main: ./cmd/tools
    binary: aixgo-tools
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: aixgo-dev
    name: aixgo
  draft: false
  prerelease: auto
  mode: append
  name_template: "v{{.Version}}"
  footer: |
    ## Installation

    **As a Library:**
    ```bash
    go get github.com/aixgo-dev/aixgo@{{.Tag}}
    ```

    **CLI Tools:**
    Download pre-built binaries for your platform from the assets above, or install via `go install`:
    ```bash
    go install github.com/aixgo-dev/aixgo/cmd/orchestrator@{{.Tag}}
    go install github.com/aixgo-dev/aixgo/cmd/benchmark@{{.Tag}}
    go install github.com/aixgo-dev/aixgo/cmd/deploy@{{.Tag}}
    go install github.com/aixgo-dev/aixgo/cmd/tools@{{.Tag}}
    ```

    **Full Changelog**: https://github.com/aixgo-dev/aixgo/compare/{{.PreviousTag}}...{{.Tag}}

# Generate SBOMs for security compliance
sboms:
  - artifacts: archive

# Sign checksums and artifacts (requires GPG key)
# signs:
#   - artifacts: checksum
#     args:
#       - "--batch"
#       - "--local-user"
#       - "{{ .Env.GPG_FINGERPRINT }}"
#       - "--output"
#       - "${signature}"
#       - "--detach-sign"
#       - "${artifact}"
