# GoReleaser configuration for Aixgo
# Tested with GoReleaser v2.13+
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: aixgo
    main: ./cmd/aixgo
    binary: aixgo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^web:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'Security'
      regexp: '^.*?(security(\([[:word:]]+\))?|fix\(security\))!?:.+$'
      order: 0
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: aixgo-dev
    name: aixgo
  draft: false
  prerelease: auto
  mode: append
  name_template: "v{{.Version}}"
  header: |
    ## Aixgo {{.Version}}

    Production-grade AI agent framework for Go.

  footer: |
    ## Installation

    **As a Go Library:**
    ```bash
    go get github.com/aixgo-dev/aixgo@{{.Tag}}
    ```

    **CLI Binary:**
    Download the pre-built binary for your platform from the assets above.

    ```bash
    # Linux/macOS
    curl -L https://github.com/aixgo-dev/aixgo/releases/download/{{.Tag}}/aixgo_{{.Version}}_Linux_x86_64.tar.gz | tar xz
    sudo mv aixgo /usr/local/bin/

    # Or install from source
    go install github.com/aixgo-dev/aixgo/cmd/aixgo@{{.Tag}}
    ```

    ---
    **Full Changelog**: https://github.com/aixgo-dev/aixgo/compare/{{.PreviousTag}}...{{.Tag}}

sboms:
  - artifacts: archive
