package proto

import (
	"context"

	"google.golang.org/grpc"
)

// Stub types for DistributedRuntime gRPC service
// TODO: Replace with generated protobuf code

// ExecuteRequest represents a request to execute an agent
type ExecuteRequest struct {
	AgentName string
	Input     *Message
}

// ExecuteResponse represents the response from agent execution
type ExecuteResponse struct {
	Output *Message
}

// SendRequest represents a request to send a message to an agent
type SendRequest struct {
	Target  string
	Message *Message
}

// SendResponse represents the response from sending a message
type SendResponse struct {
	Success bool
}

// AgentServiceClient is the client interface for the agent service
type AgentServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

// agentServiceClient implements AgentServiceClient
type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewAgentServiceClient creates a new AgentServiceClient
func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/aixgo.AgentService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/aixgo.AgentService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server interface for the agent service
type AgentServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
}

// UnimplementedAgentServiceServer provides default implementations
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, nil
}

func (UnimplementedAgentServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, nil
}

// _AgentService_Execute_Handler is the handler for the Execute RPC method
func _AgentService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aixgo.AgentService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// _AgentService_Send_Handler is the handler for the Send RPC method
func _AgentService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aixgo.AgentService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterAgentServiceServer registers the agent service with gRPC
func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// Stub implementation - would be generated by protoc
	s.RegisterService(&grpc.ServiceDesc{
		ServiceName: "aixgo.AgentService",
		HandlerType: (*AgentServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Execute",
				Handler:    _AgentService_Execute_Handler,
			},
			{
				MethodName: "Send",
				Handler:    _AgentService_Send_Handler,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "agent_service.proto",
	}, srv)
}
