package proto

import (
	"context"

	"google.golang.org/grpc"
)

// Stub types for DistributedRuntime gRPC service
// TODO: Replace with generated protobuf code

// ExecuteRequest represents a request to execute an agent
type ExecuteRequest struct {
	AgentName string
	Input     *Message
}

// ExecuteResponse represents the response from agent execution
type ExecuteResponse struct {
	Output *Message
}

// SendRequest represents a request to send a message to an agent
type SendRequest struct {
	Target  string
	Message *Message
}

// SendResponse represents the response from sending a message
type SendResponse struct {
	Success bool
}

// AgentServiceClient is the client interface for the agent service
type AgentServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

// agentServiceClient implements AgentServiceClient
type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewAgentServiceClient creates a new AgentServiceClient
func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/aixgo.AgentService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/aixgo.AgentService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server interface for the agent service
type AgentServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
}

// UnimplementedAgentServiceServer provides default implementations
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, nil
}

func (UnimplementedAgentServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, nil
}

// RegisterAgentServiceServer registers the agent service with gRPC
func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// Stub implementation - would be generated by protoc
	s.RegisterService(&grpc.ServiceDesc{
		ServiceName: "aixgo.AgentService",
		HandlerType: (*AgentServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Execute",
				Handler:    nil, // TODO: implement when needed
			},
			{
				MethodName: "Send",
				Handler:    nil, // TODO: implement when needed
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "agent_service.proto",
	}, srv)
}
