steps:
  # Install Hugo Extended
  - name: 'gcr.io/cloud-builders/wget'
    args:
      - '--quiet'
      - '-O'
      - 'hugo.tar.gz'
      - 'https://github.com/gohugoio/hugo/releases/download/v0.139.3/hugo_extended_0.139.3_linux-amd64.tar.gz'
    dir: 'web'
    id: 'download-hugo'

  # Extract Hugo
  - name: 'ubuntu'
    args:
      - 'tar'
      - '-xzf'
      - 'hugo.tar.gz'
      - 'hugo'
    dir: 'web'
    id: 'extract-hugo'

  # Build the Hugo site
  - name: 'ubuntu'
    entrypoint: './hugo'
    args:
      - '--minify'
      - '--environment'
      - 'production'
    dir: 'web'
    id: 'build-site'
    env:
      - 'HUGO_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'HUGO_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'HUGO_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'HUGO_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - 'HUGO_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - 'HUGO_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
      - 'HUGO_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}'

  # Install Firebase CLI and deploy to Firebase Hosting
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project aixgo-dev --non-interactive
    dir: 'web'
    id: 'deploy-to-firebase'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _FIREBASE_API_KEY: ''
  _FIREBASE_AUTH_DOMAIN: ''
  _FIREBASE_PROJECT_ID: ''
  _FIREBASE_STORAGE_BUCKET: ''
  _FIREBASE_MESSAGING_SENDER_ID: ''
  _FIREBASE_APP_ID: ''
  _FIREBASE_MEASUREMENT_ID: ''

timeout: '600s'
