steps:
  # Install Hugo Extended
  - name: 'gcr.io/cloud-builders/wget'
    args:
      - '--quiet'
      - '-O'
      - 'hugo.tar.gz'
      - 'https://github.com/gohugoio/hugo/releases/download/v0.139.3/hugo_extended_0.139.3_linux-amd64.tar.gz'
    dir: 'web'
    id: 'download-hugo'

  # Extract Hugo
  - name: 'ubuntu'
    args:
      - 'tar'
      - '-xzf'
      - 'hugo.tar.gz'
      - 'hugo'
    dir: 'web'
    id: 'extract-hugo'

  # Build the Hugo site
  - name: 'ubuntu'
    entrypoint: './hugo'
    args:
      - '--minify'
      - '--environment'
      - 'production'
    dir: 'web'
    id: 'build-site'

  # Install Firebase CLI and deploy to Firebase Hosting
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project aixgo-dev --non-interactive
    dir: 'web'
    id: 'deploy-to-firebase'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '600s'
